name: docker-build-and-push
description: ""

inputs:
  bake-target:
    description: ""
    required: true
  build-args:
    description: ""
    required: true
  tag-prefix:
    description: ""
    required: true
  dockerhub-token:
    description: ""
    required: true

runs:
  using: composite
  steps:
    - name: Set Docker tags
      id: set-docker-tags
      run: |
        tags=()
        tags+=("latest")
        tags+=("latest-${{ inputs.tag-prefix }}")
        tags+=("{{date 'YYYYMMDD'}}")
        tags+=("{{date 'YYYYMMDD'}}-${{ inputs.tag-prefix }}")

        # Output multiline strings: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "tags<<$EOF" >> $GITHUB_OUTPUT
        echo "$(printf "%s\n" "${tags[@]}")" >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Docker meta for autoware-core-base
      id: meta-autoware-core-base
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-autoware-core-base
        flavor: |
          latest=false
          suffix=-autoware-core-base

    - name: Docker meta for autoware-universe-base
      id: meta-autoware-universe-base
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-autoware-universe-base
        flavor: |
          latest=false
          suffix=-autoware-universe-base

    - name: Docker meta for runtime-base
      id: meta-runtime-base
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository_owner }}/${{ inputs.bake-target }}
        tags: ${{ steps.set-docker-tags.outputs.tags }}
        bake-target: docker-metadata-action-runtime-base
        flavor: |
          latest=true
          suffix=-runtime-base

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ inputs.dockerhub-token }}

    - name: Build and Push to GitHub Container Registry
      uses: docker/bake-action@v5
      with:
        push: true
        files: |
          docker-bake.hcl
          ${{ steps.meta-autoware-core-base.outputs.bake-file }}
          ${{ steps.meta-autoware-universe-base.outputs.bake-file }}
          ${{ steps.meta-runtime-base.outputs.bake-file }}
        provenance: false
        set: |
          ${{ inputs.build-args }}
