name: docker-build-and-push

on:
  push:
    branches:
      - main
    tags:
  workflow_dispatch:

jobs:
  load-env:
    uses: ./.github/workflows/load-env.yaml

  docker-build-and-push:
    needs: load-env
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install vcstool
        run: |
          sudo apt-get -y update
          sudo apt-get -y install python3-pip
          pip install --no-cache-dir vcstool
        shell: bash

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Run vcs import
        run: |
          wget -O autoware.repos https://raw.githubusercontent.com/autowarefoundation/autoware/main/autoware.repos
          mkdir src
          vcs import src < autoware.repos
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Autoware's base images
        uses: ./.github/actions/docker-build-and-push
        with:
          bake-target: autoware-base
          build-args: |
            *.platform=linux/amd64,linux/arm64
            *.args.ROS_DISTRO=${{ needs.load-env.outputs.rosdistro }}
            *.args.BASE_IMAGE=${{ needs.load-env.outputs.base_image }}
          tag-prefix: ${{ needs.load-env.outputs.rosdistro }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
